### ISSUE TITLE
Add more specific location for encrypted secret 

### ISSUE THREAD

**Issue by ghost** [Apon77/aosp-builder#1]
by (cirrus ci repository ) in the file .cirrus.yml  i got confused with the github repo for cirrus or the cirrus website itself so please providing more specific documentation for encrypted credentials will be nice

btw nice project

**Comment by Apon77** [comment]
After pushing first commit and build, Login in https://cirrus-ci.com
Then top left corner 3 dot menu,, you will find your repository name,, 
Click it and go to your repository. There is setting icon for that repo,, then you can add encrypted secret.. Hope it will clear the confusion! Will try adding this in documents! 

And thanks for complement! ❤️

**Comment by ghost** [comment]
> After pushing first commit and build, Login in https://cirrus-ci.com
> Then top left corner 3 dot menu,, you will find your repository name,,
> Click it and go to your repository. There is setting icon for that repo,, then you can add encrypted secret.. Hope it will clear the confusion! Will try adding this in documents!
> 
> And thanks for complement! ❤️

yes i got the solution in past only btw tq to add to docs iam closing this issue
